apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bhuvanesh726/event-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          # IMPORTANT: Pointing to the new Backend NodePort
          env:
            - name: VITE_API_BASE_URL
              value: "http://localhost:30005"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  # CHANGED: Use NodePort for explicit port mapping
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173 # Internal Cluster Port
      targetPort: 5173 # Container Port
      nodePort: 30006 # EXTERNAL PORT (Windows)
